django/cdash_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from importlib import util, import_module

urlpatterns = [
    path('', include('controlframework.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]



# Automatically load urlpatterns for each installed app
for app in settings.APP_LIST:
    if util.find_spec(app + ".urls") is not None:
        urls = import_module(app + ".urls")
        urlpatterns.append(path(urls.app_name + '/', include(app + '.urls')))

django/controlframework/urls.py
from django.urls import path
from . import views

app_name = 'cf'
urlpatterns = [
	path('', views.dashboard, name='dashboard'),
	path('dashboard/', views.dashboard, name='dashboard'),

	path('controlframework', views.ControlFrameworkListView.as_view(), name='controlframework'),

	path('policies', views.DomainListView.as_view(), name='policies'),
	
	path('policies/domain/<int:pk>', views.DomainView.as_view(), name='policies/domain'),
	path('policies/domain/add/', views.DomainCreate.as_view(), name='policies/domain/add'),
	path('policies/domain/<int:pk>/update/', views.DomainUpdate.as_view(), name='policies/domain/update'),
	path('policies/domain/<int:pk>/delete/', views.DomainDelete.as_view(), name='policies/domain/delete'),

	path('policies/genericpolicy/<int:pk>', views.GenericPolicyView.as_view(), name='policies/genericpolicy'),
	path('policies/genericpolicy/add/domain/<int:domain_id>', views.GenericPolicyCreate.as_view(), name='policies/genericpolicy/add/domain'),
	path('policies/genericpolicy/<int:pk>/update', views.GenericPolicyUpdate.as_view(), name='policies/genericpolicy/update'),
	path('policies/genericpolicy/<int:pk>/delete', views.GenericPolicyDelete.as_view(), name='policies/genericpolicy/delete'),

	path('policies/policy/<int:pk>', views.PolicyView.as_view(), name='policies/policy'),
	path('policies/policy/add/genericpolicy/<int:genericpolicy_id>', views.PolicyCreate.as_view(), name='policies/policy/add/genericpolicy'),
	path('policies/policy/update/<int:pk>', views.PolicyUpdate.as_view(), name='policies/policy/update'),
	path('policies/policy/delete/<int:pk>', views.PolicyDelete.as_view(), name='policies/policy/delete'),

	path('controls/', views.GenericControlListView.as_view(),name='controls'),
	
	path('controls/genericcontrol/<int:pk>/', views.GenericControlView.as_view(),name='controls/genericcontrol'),
	path('controls/genericcontrol/add/', views.GenericControlCreate.as_view(),name='controls/genericcontrol/add'),
	path('controls/genericcontrol/<int:pk>/update/', views.GenericControlUpdate.as_view(),name='controls/genericcontrol/update'),
	path('controls/genericcontrol/<int:pk>/delete/', views.GenericControlDelete.as_view(),name='controls/genericcontrol/delete'),
	
	path('controls/control/<int:pk>/', views.ControlView.as_view(),name='controls/control'),
	path('controls/control/add/genericcontrol/<int:genericcontrol_id>/', views.ControlCreate.as_view(),name='controls/control/add/genericcontrol'),
	path('controls/control/<int:pk>/update/', views.ControlUpdate.as_view(),name='controls/control/update'),
	path('controls/control/<int:pk>/delete/', views.ControlDelete.as_view(),name='controls/control/delete'),


	path('objects/', views.GenericObjectListView.as_view(),name='objects'),
	
	path('objects/genericobject/<int:pk>/', views.GenericObjectView.as_view(),name='objects/genericobject'),
	path('objects/genericobject/add/', views.GenericObjectCreate.as_view(),name='objects/genericobject/add'),
	path('objects/genericobject/<int:pk>/update/', views.GenericObjectUpdate.as_view(),name='objects/genericobject/update'),
	path('objects/genericobject/<int:pk>/delete/', views.GenericObjectDelete.as_view(),name='objects/genericobject/delete'),
	
	path('objects/object/<int:pk>/', views.ObjectView.as_view(),name='objects/object'),
	path('objects/object/add/genericobject/<int:genericobject_id>/', views.ObjectCreate.as_view(),name='objects/object/add/genericobject'),
	path('objects/object/<int:pk>/update/', views.ObjectUpdate.as_view(),name='objects/object/update'),
	path('objects/object/<int:pk>/delete/', views.ObjectDelete.as_view(),name='objects/object/delete'),
]

django/controlframework/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django_celery_beat.models import CrontabSchedule

def get_name(self):
    return self.first_name+" "+self.last_name

User.add_to_class("__str__", get_name)


class Domain(models.Model):
    number = models.IntegerField(unique=True)
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    link = models.CharField(max_length=500, blank=True)

    def __str__(self):
        return str(self.number)+" "+self.name

    def get_absolute_url(self):
        return reverse('cf:policies/domain', kwargs={'pk':self.pk})

    class Meta:
        ordering = ['number']
        verbose_name = 'Domain'
        verbose_name_plural = 'Domains'

class GenericPolicy(models.Model):
    domain = models.ForeignKey(Domain, related_name='generic_policies', on_delete=models.PROTECT)
    number = models.IntegerField()
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    link = models.CharField(max_length=500, blank=True)

    def __str__(self):
        return str(self.domain.number)+"."+str(self.number)+" "+self.name

    def get_absolute_url(self):
        return reverse('cf:policies/genericpolicy', kwargs={'pk':self.pk})

    @property
    def parent(self):
        return self.domain

    class Meta:
        ordering = ['domain', 'number']
        unique_together = ('domain','number')
        verbose_name = 'Generic Policy'
        verbose_name_plural = 'Generic Policies'

class GenericObject(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    link = models.CharField(max_length=500, blank=True)
    #owner = models.ForeignKey(User, related_name='genericobjects', on_delete=models.PROTECT)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('cf:objects/genericobject', kwargs={'pk':self.pk})

    class Meta:
        ordering = ['name']
        verbose_name = 'Generic Object'
        verbose_name_plural = 'Generic Objects'

class Object(models.Model):
    generic_object = models.ForeignKey(GenericObject, related_name='objects', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    link = models.CharField(max_length=500, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('cf:objects/object', kwargs={'pk':self.pk})

    @property
    def parent(self):
        return self.generic_object

    class Meta:
        ordering = ['generic_object', 'name']
        verbose_name = 'Object'
        verbose_name_plural = 'Objects'

class Policy(models.Model):
    generic_policy = models.ForeignKey(GenericPolicy, related_name='policies', on_delete=models.PROTECT)
    generic_object = models.ForeignKey(GenericObject, related_name ='policies', on_delete=models.PROTECT)
    owner = models.ForeignKey(User, related_name='owned_policies', on_delete=models.PROTECT)
    accountable = models.ForeignKey(User, related_name='accountable_policies', on_delete=models.PROTECT)
    narrative = models.URLField(max_length=300, blank=True)

    def __str__(self):
        return str(self.generic_policy)+" - "+str(self.generic_object)

    def get_absolute_url(self):
        return reverse('cf:policies/policy', kwargs={'pk':self.pk})

    @property
    def parent(self):
        return self.generic_policy

    class Meta:
        ordering = ['generic_policy', 'generic_object']
        unique_together = ('generic_policy','generic_object')
        verbose_name = 'Policy'
        verbose_name_plural = 'Policies'

class GenericControl(models.Model):
    generic_policy = models.ForeignKey(GenericPolicy, related_name='generic_controls', on_delete=models.PROTECT)
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    link = models.CharField(max_length=500, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('cf:controls/genericcontrol', kwargs={'pk':self.pk})

    class Meta:
        ordering = ['name']
        verbose_name = 'Generic Control'
        verbose_name_plural = 'Generic Controls'

class Criticality(models.Model):
    value = models.CharField(max_length=200)

    def __str__(self):
        return self.value

    class Meta:
        verbose_name = 'Criticality'
        verbose_name_plural = 'Criticalities'

class Frequency(models.Model):
    number = models.IntegerField()
    value = models.CharField(max_length=200)
    duration = models.IntegerField()
    cron = models.ForeignKey(CrontabSchedule, on_delete=models.PROTECT, null=True) # to do: make non-nullable

    def __str__(self):
        return self.value

    '''def get_interval(self):
        interval = {
            'year': self.interval.get('year', 0),
            'month': self.interval.get('month', 0),
            'week': self.interval.get('week', 0),
            'day': self.interval.get('day', 0),
            'hour': self.interval.get('hour', 0),
            'minute': self.interval.get('minute', 0)
        }
        return interval'''

    class Meta:
        ordering = ['number']
        verbose_name = 'Frequency'
        verbose_name_plural = 'Frequencies'

class Control(models.Model):
    KEY = 1
    NON_KEY = 2
    NA = 3

    CRITICALITY_CHOICES = [
        (KEY, 'Key'),
        (NON_KEY, 'Non key'),
        (NA, 'N/A'),
    ]

    generic_control = models.ForeignKey(GenericControl, related_name='controls', on_delete=models.PROTECT)
    object = models.ForeignKey(Object, on_delete=models.PROTECT)
    owner = models.ForeignKey(User, related_name='controls', on_delete=models.PROTECT)
    sox = models.IntegerField(choices=CRITICALITY_CHOICES)
    pci = models.IntegerField(choices=CRITICALITY_CHOICES)
    frequency = models.ForeignKey(Frequency, related_name='controls', on_delete=models.PROTECT)
    custom_duration = models.IntegerField(blank=True, null=True)
    search_string = models.CharField(max_length=10000, blank=True)

    def __str__(self):
        return str(self.generic_control)+" - "+str(self.object)

    def get_absolute_url(self):
        return reverse('cf:controls/control', kwargs={'pk':self.pk})
    
    @property
    def parent(self):
        return self.generic_control

    @property
    def duration(self):
        if self.custom_duration is None:
            return self.frequency.duration
        else:
            return self.custom_duration

    @property
    def policy(self):
        return Policy.objects.filter(generic_policy=self.generic_control.generic_policy,generic_object=self.object.generic_object).first

    class Meta:
        ordering = ['generic_control', 'object']
        unique_together = ('generic_control','object')
        verbose_name = 'Control'
        verbose_name_plural = 'Controls'

django/controlframework/forms.py
from django import forms
from cdash_project.forms import StandardForm
from .models import Domain, GenericPolicy, Policy, GenericObject, Object, GenericControl, Control


class DomainForm(StandardForm):

    class Meta:
        model = Domain
        fields = "__all__"

class GenericPolicyForm(StandardForm):

    class Meta:
        model = GenericPolicy
        fields = "__all__"

class PolicyForm(StandardForm):

    class Meta:
        model = Policy
        fields = "__all__"

class GenericObjectForm(StandardForm):

    class Meta:
        model = GenericObject
        fields = "__all__"

class ObjectForm(StandardForm):

    class Meta:
        model = Object
        fields = "__all__"

class GenericControlForm(StandardForm):

    class Meta:
        model = GenericControl
        fields = "__all__"

class ControlForm(StandardForm):

    class Meta:
        model = Control
        fields = "__all__"

django/controlframework/views/views_controlframework.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import render 
from django.views.generic import ListView

from ..models import Control
from .. import navigation

def dashboard(request):
	return render(request, 'controlframework/dashboard.html',{'title': 'dashboard', 'nav_dashboard': 'active'})

## Control Framework

class ControlFrameworkListView(PermissionRequiredMixin, ListView):
	permission_required = 'controlframework.view_control'
	model = Control
	template_name = 'controlframework/controlframework/controlframework.html'
	nav_item_active = navigation.app.nav_items['controlframework']

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['title'] = 'Control Framework'
		context['nav_item_active'] = self.nav_item_active
		return context

django/controlframework/templates/controlframework/objects/genericobject.html
{% extends 'base.html' %}

{% block content %}

<!-- Begin Page Content -->
<div class="container-fluid">

	<!-- Page Heading -->
	<div class="d-flex align-items-center justify-content-between mb-4">

		<nav aria-label="breadcrumb">
			<ol class="breadcrumb mb-0">
				<li class="breadcrumb-item"><a href="{% url 'cf:objects' %}">Objects</a></li>
				<li class="breadcrumb-item active" aria-current="page">{{ genericobject }}</li>
			</ol>
		</nav>
	</div>

	<div class="row">
		<div class="col-lg-6">
			<!-- Generc Object Card -->
			<div class="card shadow mb-4">
				<!-- Card Header -->
				<div class="card-header py-3">
					<div class="d-flex align-items-center justify-content-between mb-0">
						<!-- Generic Object-->
						<h6 class="m-0 font-weight-bold text-primary">{{ genericobject.name }}</h6>
						<div>
							{% if perms.controlframework.add_object %}
							<!-- Button - New -->
							<a href="{% url 'cf:objects/object/add/genericobject' genericobject.id %}" class="btn btn-primary btn-icon-split btn-sm">
								<span class="icon text-white-50">
									<i class="fas fa-plus"></i>
								</span>
								<span class="text d-none d-sm-block">New Object</span>
							</a>
							{% endif %}
							{% if perms.contorlframework.delete_genericobject %}
							<!-- Button - Delete -->
							<a href="{% url 'cf:objects/genericobject/delete' genericobject.id %}" class="btn btn-primary btn-icon-split btn-sm">
								<span class="icon text-white-50">
									<i class="fas fa-trash"></i>
								</span>
								<span class="text d-none d-sm-block">Delete</span>
							</a>
							{% endif %}
							{% if perms.change_genericobject %}
							<!-- Button - Edit -->
							<a href="{% url 'cf:objects/genericobject/update' genericobject.id %}" class="btn btn-primary btn-icon-split btn-sm">
								<span class="icon text-white-50">
									<i class="fas fa-edit"></i>
								</span>
								<span class="text d-none d-sm-block">Edit</span>
							</a>
							{% endif %}
						</div>
					</div>
				</div>
				<!-- Card Body -->
				<div class="card-body">
					<p>
						<span class="small">Description</span><br>
						{{ genericobject.description | linebreaks }}
					</p>
					<p>
						<span class="small">Linked Objects</span><br>
						{% for object in genericobject.objects.all %}
						<a class="float-left text-secondary" href="{{ object.get_absolute_url }}">{{ object }}</a>
						<span class="float-right">test</span><br>
						{% endfor %}
					</p>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock content %}

django/controlframework/templates/controlframework/objects/object.html
{% extends 'base.html' %}

{% block content %}

<!-- Begin Page Content -->
<div class="container-fluid">

	<!-- Page Heading -->
	<div class="d-flex align-items-center justify-content-between mb-4">
		<nav aria-label="breadcrumb">
			<ol class="breadcrumb mb-0">
				<li class="breadcrumb-item"><a href="{% url 'cf:objects' %}">Objects</a></li>
				<li class="breadcrumb-item"><a href="{{ object.generic_object.get_absolute_url }}">{{ object.generic_object }}</a></li>
				<li class="breadcrumb-item active" aria-current="page">{{ object }}</li>
			</ol>
		</nav>
	</div>

	<div class="row">
		<div class="col-lg-6">
			<!-- Info Card -->
			<div class="card shadow mb-4">
				<div class="card-header py-3">
					<div class="d-flex align-items-center justify-content-between mb-0">
						<h6 class="m-0 font-weight-bold text-primary">{{ object.name }}</h6>
						<div>
							{% if perms.controlframework.delete_object %}
							<!-- Button - Delete -->
							<a href="{% url 'cf:objects/object/delete' object.id %}" class="btn btn-primary btn-icon-split btn-sm">
								<span class="icon text-white-50">
									<i class="fas fa-trash"></i>
								</span>
								<span class="text d-none d-sm-block">Delete</span>
							</a>
							{% endif %}
							{% if perms.controlframework.change_object %}
							<!-- Button - Edit -->
							<a href="{% url 'cf:objects/object/update' object.id %}" class="btn btn-primary btn-icon-split btn-sm">
								<span class="icon text-white-50">
									<i class="fas fa-edit"></i>
								</span>
								<span class="text d-none d-sm-block">Edit</span>
							</a>
							{% endif %}
						</div>
					</div>
				</div>
				<!-- Default Card Example -->
				<div class="card-body">
					<p>
						<!--<span style="font-weight:lighter; font-style: italic">-->
						<span class="small">Description</span><br>
						{{ object.description | linebreaks }}
					</p>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock content %}

django/controlframework/templates/controlframework/objects/objects.html
{% extends 'base.html' %}

{% block content %}

<!-- Begin Page Content -->
<div class="container-fluid">

	<!-- Modal -->
	{% block modal %}
	{% include 'controlframework/objects_modal.html' %}
	{% endblock %}

	<!-- Page Heading -->
	<div class="d-flex align-items-center justify-content-between mb-4">
		<nav aria-label="breadcrumb">
			<ol class="breadcrumb mb-0">
				<li class="breadcrumb-item"><a href="{% url 'cf:objects' %}">Objects</a></li>
			</ol>
		</nav>
		<div>
			{% if perms.controlframework.add_genericobject %}
			<!-- Button - New -->
			<a href="{% url 'cf:objects/genericobject/add' %}" class="btn btn-primary btn-icon-split btn-sm">
				<span class="icon text-white-50">
					<i class="fas fa-plus"></i>
				</span>
				<span class="text d-none d-sm-block">New Generic Object</span>
			</a>
			{% endif %}
		</div>
	</div>

	<!-- Page Body -->
	<div class="row">
		<div class="col-lg-6">

			{% for genericobject in genericobject_list %}
			<!-- Object Card -->
			<div class="card shadow mb-4">
				<!-- Card Header - Generic Object -->
				<div class="card-header py-3">
					<h6 class="m-0 font-weight-bold text-primary">
						<a href="{{ genericobject.get_absolute_url }}">
							{{genericobject}}
						</a>
					</h6>
				</div>
				<!-- Card Content - Objects -->
				<div class="card-body">

					{% for object in genericobject.objects.all %}
					<a class="float-left text-secondary" href="{{ object.get_absolute_url }}">{{ object }}</a>
					<span class="float-right">test</span><br>
					{% endfor %}

				</div>
			</div>
			{% endfor %}
			

		</div>
		<div class="col-lg-6">

			<!-- Info Card -->
			<div class="card shadow mb-4">
				<div class="card-header py-3">
					Control Info
				</div>
				<!-- Default Card Example -->
				<div class="card-body">
					This card uses Bootstrap's default styling with no utility classes added. Global styles are the only things modifying the look and feel of this default card example.
				</div>
			</div>

		</div>
	</div>
</div>

{% endblock content %}