django/cdash_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from importlib import util, import_module

urlpatterns = [
    path('', include('controlframework.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]



# Automatically load urlpatterns for each installed app
for app in settings.APP_LIST:
    if util.find_spec(app + ".urls") is not None:
        urls = import_module(app + ".urls")
        urlpatterns.append(path(urls.app_name + '/', include(app + '.urls')))

django/controlframework/urls.py
from django.urls import path
from . import views

app_name = 'cf'
urlpatterns = [
	path('', views.dashboard, name='dashboard'),
	path('dashboard/', views.dashboard, name='dashboard'),

	path('controlframework', views.ControlFrameworkListView.as_view(), name='controlframework'),

	path('policies', views.DomainListView.as_view(), name='policies'),
	
	path('policies/domain/<int:pk>', views.DomainView.as_view(), name='policies/domain'),
	path('policies/domain/add/', views.DomainCreate.as_view(), name='policies/domain/add'),
	path('policies/domain/<int:pk>/update/', views.DomainUpdate.as_view(), name='policies/domain/update'),
	path('policies/domain/<int:pk>/delete/', views.DomainDelete.as_view(), name='policies/domain/delete'),

	path('policies/genericpolicy/<int:pk>', views.GenericPolicyView.as_view(), name='policies/genericpolicy'),
	path('policies/genericpolicy/add/domain/<int:domain_id>', views.GenericPolicyCreate.as_view(), name='policies/genericpolicy/add/domain'),
	path('policies/genericpolicy/<int:pk>/update', views.GenericPolicyUpdate.as_view(), name='policies/genericpolicy/update'),
	path('policies/genericpolicy/<int:pk>/delete', views.GenericPolicyDelete.as_view(), name='policies/genericpolicy/delete'),

	path('policies/policy/<int:pk>', views.PolicyView.as_view(), name='policies/policy'),
	path('policies/policy/add/genericpolicy/<int:genericpolicy_id>', views.PolicyCreate.as_view(), name='policies/policy/add/genericpolicy'),
	path('policies/policy/update/<int:pk>', views.PolicyUpdate.as_view(), name='policies/policy/update'),
	path('policies/policy/delete/<int:pk>', views.PolicyDelete.as_view(), name='policies/policy/delete'),

	path('controls/', views.GenericControlListView.as_view(),name='controls'),
	
	path('controls/genericcontrol/<int:pk>/', views.GenericControlView.as_view(),name='controls/genericcontrol'),
	path('controls/genericcontrol/add/', views.GenericControlCreate.as_view(),name='controls/genericcontrol/add'),
	path('controls/genericcontrol/<int:pk>/update/', views.GenericControlUpdate.as_view(),name='controls/genericcontrol/update'),
	path('controls/genericcontrol/<int:pk>/delete/', views.GenericControlDelete.as_view(),name='controls/genericcontrol/delete'),
	
	path('controls/control/<int:pk>/', views.ControlView.as_view(),name='controls/control'),
	path('controls/control/add/genericcontrol/<int:genericcontrol_id>/', views.ControlCreate.as_view(),name='controls/control/add/genericcontrol'),
	path('controls/control/<int:pk>/update/', views.ControlUpdate.as_view(),name='controls/control/update'),
	path('controls/control/<int:pk>/delete/', views.ControlDelete.as_view(),name='controls/control/delete'),


	path('objects/', views.GenericObjectListView.as_view(),name='objects'),
	
	path('objects/genericobject/<int:pk>/', views.GenericObjectView.as_view(),name='objects/genericobject'),
	path('objects/genericobject/add/', views.GenericObjectCreate.as_view(),name='objects/genericobject/add'),
	path('objects/genericobject/<int:pk>/update/', views.GenericObjectUpdate.as_view(),name='objects/genericobject/update'),
	path('objects/genericobject/<int:pk>/delete/', views.GenericObjectDelete.as_view(),name='objects/genericobject/delete'),
	
	path('objects/object/<int:pk>/', views.ObjectView.as_view(),name='objects/object'),
	path('objects/object/add/genericobject/<int:genericobject_id>/', views.ObjectCreate.as_view(),name='objects/object/add/genericobject'),
	path('objects/object/<int:pk>/update/', views.ObjectUpdate.as_view(),name='objects/object/update'),
	path('objects/object/<int:pk>/delete/', views.ObjectDelete.as_view(),name='objects/object/delete'),
]

django/controlexecution/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime, date
from django_celery_beat.models import PeriodicTask, CrontabSchedule

from controlframework.models import Control

class ControlTask(models.Model):
    control = models.OneToOneField(Control, related_name="control_task", on_delete=models.CASCADE)

    issue_id = models.IntegerField(blank=True, null=True);
    issue_key = models.CharField(max_length=20, blank=True, null=True);

    def get_tasks_per_status(self):
        tasks = {}
        for calculated_status in Task.CALCULATED_STATUSES:
                nr_tasks = self.tasks.filter(calculated_status=calculated_status[0]).count()
                if ((not calculated_status[0] == Task.DONE and nr_tasks > 0)
                    or (not tasks and calculated_status[0] == Task.DONE)):
                        tasks[calculated_status[1]] = {
                            'nr_tasks': nr_tasks,
                            'label_color': Task.LABEL_COLORMAP[calculated_status[0]],
                        }
        return tasks

    def __str__(self):
        return str("Control task for {}".format(self.control))

    class Meta:
            verbose_name = 'Control Task'
            verbose_name_plural = 'Control Tasks'

class ScheduledTask(models.Model):
    enabled = models.BooleanField(default = True)
    initial_run = models.BooleanField(default = False)

    control_task = models.OneToOneField(ControlTask, related_name="scheduled_task", on_delete=models.CASCADE)

    description = models.TextField(max_length=5000, blank=True, null=True)
    assignee = models.CharField(max_length=254, blank=True, null=True)
    watchers = models.CharField(max_length=500, blank=True, null=True)
    start_date = models.DateTimeField(blank=True, null=True)
    end_date = models.DateTimeField(blank=True, null=True)
    custom_cron = models.ForeignKey(CrontabSchedule, on_delete=models.PROTECT, blank=True, null=True)

    celery_periodic_task = models.OneToOneField(PeriodicTask, related_name='scheduled_task', on_delete=models.CASCADE, blank=True, null=True)

    @property
    def summary(self):
        summary = f"{self.control_task.control} | {datetime.now().strftime('%Y-%m-%d')}"
        return summary

    @property
    def cron(self):
        if self.custom_cron:
            return self.custom_cron
        else:
            return self.control_task.control.frequency.cron

    def __str__(self):
        return str("Scheduled task for {}".format(self.control_task.control))

    class Meta:
        verbose_name = 'Scheduled Task'
        verbose_name_plural = 'Scheduled Tasks'

class Task(models.Model):
    OVERDUE = 2
    NEARLY_DUE = 3
    TO_DO = 4
    DONE = 1

    CALCULATED_STATUSES = (
        (OVERDUE, 'Overdue'),
        (NEARLY_DUE, 'Nearly Due'),
        (TO_DO, 'To Do'),
        (DONE, 'Done'),
    )

    JIRA_STATUSES = {
        TO_DO: 'To Do',
        DONE: 'Done',
    }

    LABEL_COLORMAP = {
        OVERDUE: 'danger',
        NEARLY_DUE: 'warning',
        TO_DO: 'primary',
        DONE: 'success',
    }

    control_task = models.ForeignKey(ControlTask, related_name='tasks', on_delete=models.CASCADE, null=True)

    issue_id = models.IntegerField(unique=True)
    issue_key = models.CharField(max_length=20)
    issue_type = models.CharField(max_length=254, blank=True, null=True)

    summary = models.CharField(max_length=254, blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    assignee_username = models.CharField(max_length=254, blank=True, null=True)
    assignee_displayname = models.CharField(max_length=254, blank=True, null=True)

    compliance_id = models.CharField(max_length=254, blank=True, null=True)

    status_category = models.CharField(max_length=254, blank=True, null=True)
    status = models.CharField(max_length=254, blank=True, null=True)
    created_date = models.DateTimeField(auto_now=False, auto_now_add=False)
    due_date = models.DateField(auto_now=False, auto_now_add=False, blank=True, null=True)
    resolution_date = models.CharField(max_length=254, blank=True, null=True)

    calculated_status = models.IntegerField(choices=CALCULATED_STATUSES, default = TO_DO)

    def save(self, *args, **kwargs):
        self.calculated_status = self.calculate_status()
        super(Task, self).save(*args, **kwargs)

    def calculate_status(self):
        if self.status_category == self.JIRA_STATUSES[self.DONE]:
            calculated_status = self.DONE
        elif self.due_date and self.due_date < date.today():
            calculated_status = self.OVERDUE
        elif self.due_date and self.is_nearly_due():
            calculated_status = self.NEARLY_DUE
        else:
            calculated_status = self.TO_DO
        return calculated_status
    
    def get_absolute_url(self):
        return reverse('ce:tasks/task', kwargs={'pk':self.pk})

    def is_nearly_due(self):
        #todo: implement lookup table for days left per frequency
        if (self.get_days_left() < 10):
            return True
        else:
            return False

    def get_calculated_status_label_color(self):
        return self.LABEL_COLORMAP[self.calculated_status]

    def get_days_left(self):
        if not self.status_category == self.JIRA_STATUSES[self.DONE] and self.due_date:
            return (self.due_date - date.today()).days
        else:
            return ''

    def get_created_date(self):
        return self.created_date.strftime('%Y-%m-%d')

    def get_due_date(self):
        if self.due_date:
            return self.due_date.strftime('%Y-%m-%d')

    def update_statuses():
        for task in Task.objects.exclude(calculated_status=Task.DONE):
            task.save()

    def __str__(self):
        return str(self.issue_key)

    class Meta:
        ordering = ['-created_date']
        verbose_name = 'Task'
        verbose_name_plural = 'Tasks'

django/controlframework/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django_celery_beat.models import CrontabSchedule

def get_name(self):
    return self.first_name+" "+self.last_name

User.add_to_class("__str__", get_name)


class Domain(models.Model):
    number = models.IntegerField(unique=True)
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    link = models.CharField(max_length=500, blank=True)

    def __str__(self):
        return str(self.number)+" "+self.name

    def get_absolute_url(self):
        return reverse('cf:policies/domain', kwargs={'pk':self.pk})

    class Meta:
        ordering = ['number']
        verbose_name = 'Domain'
        verbose_name_plural = 'Domains'

class GenericPolicy(models.Model):
    domain = models.ForeignKey(Domain, related_name='generic_policies', on_delete=models.PROTECT)
    number = models.IntegerField()
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    link = models.CharField(max_length=500, blank=True)

    def __str__(self):
        return str(self.domain.number)+"."+str(self.number)+" "+self.name

    def get_absolute_url(self):
        return reverse('cf:policies/genericpolicy', kwargs={'pk':self.pk})

    @property
    def parent(self):
        return self.domain

    class Meta:
        ordering = ['domain', 'number']
        unique_together = ('domain','number')
        verbose_name = 'Generic Policy'
        verbose_name_plural = 'Generic Policies'

class GenericObject(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    link = models.CharField(max_length=500, blank=True)
    #owner = models.ForeignKey(User, related_name='genericobjects', on_delete=models.PROTECT)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('cf:objects/genericobject', kwargs={'pk':self.pk})

    class Meta:
        ordering = ['name']
        verbose_name = 'Generic Object'
        verbose_name_plural = 'Generic Objects'

class Object(models.Model):
    generic_object = models.ForeignKey(GenericObject, related_name='objects', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    link = models.CharField(max_length=500, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('cf:objects/object', kwargs={'pk':self.pk})

    @property
    def parent(self):
        return self.generic_object

    class Meta:
        ordering = ['generic_object', 'name']
        verbose_name = 'Object'
        verbose_name_plural = 'Objects'

class Policy(models.Model):
    generic_policy = models.ForeignKey(GenericPolicy, related_name='policies', on_delete=models.PROTECT)
    generic_object = models.ForeignKey(GenericObject, related_name ='policies', on_delete=models.PROTECT)
    owner = models.ForeignKey(User, related_name='owned_policies', on_delete=models.PROTECT)
    accountable = models.ForeignKey(User, related_name='accountable_policies', on_delete=models.PROTECT)
    narrative = models.URLField(max_length=300, blank=True)

    def __str__(self):
        return str(self.generic_policy)+" - "+str(self.generic_object)

    def get_absolute_url(self):
        return reverse('cf:policies/policy', kwargs={'pk':self.pk})

    @property
    def parent(self):
        return self.generic_policy

    class Meta:
        ordering = ['generic_policy', 'generic_object']
        unique_together = ('generic_policy','generic_object')
        verbose_name = 'Policy'
        verbose_name_plural = 'Policies'

class GenericControl(models.Model):
    generic_policy = models.ForeignKey(GenericPolicy, related_name='generic_controls', on_delete=models.PROTECT)
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    link = models.CharField(max_length=500, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('cf:controls/genericcontrol', kwargs={'pk':self.pk})

    class Meta:
        ordering = ['name']
        verbose_name = 'Generic Control'
        verbose_name_plural = 'Generic Controls'

class Criticality(models.Model):
    value = models.CharField(max_length=200)

    def __str__(self):
        return self.value

    class Meta:
        verbose_name = 'Criticality'
        verbose_name_plural = 'Criticalities'

class Frequency(models.Model):
    number = models.IntegerField()
    value = models.CharField(max_length=200)
    duration = models.IntegerField()
    cron = models.ForeignKey(CrontabSchedule, on_delete=models.PROTECT, null=True) # to do: make non-nullable

    def __str__(self):
        return self.value

    '''def get_interval(self):
        interval = {
            'year': self.interval.get('year', 0),
            'month': self.interval.get('month', 0),
            'week': self.interval.get('week', 0),
            'day': self.interval.get('day', 0),
            'hour': self.interval.get('hour', 0),
            'minute': self.interval.get('minute', 0)
        }
        return interval'''

    class Meta:
        ordering = ['number']
        verbose_name = 'Frequency'
        verbose_name_plural = 'Frequencies'

class Control(models.Model):
    KEY = 1
    NON_KEY = 2
    NA = 3

    CRITICALITY_CHOICES = [
        (KEY, 'Key'),
        (NON_KEY, 'Non key'),
        (NA, 'N/A'),
    ]

    generic_control = models.ForeignKey(GenericControl, related_name='controls', on_delete=models.PROTECT)
    object = models.ForeignKey(Object, on_delete=models.PROTECT)
    owner = models.ForeignKey(User, related_name='controls', on_delete=models.PROTECT)
    sox = models.IntegerField(choices=CRITICALITY_CHOICES)
    pci = models.IntegerField(choices=CRITICALITY_CHOICES)
    frequency = models.ForeignKey(Frequency, related_name='controls', on_delete=models.PROTECT)
    custom_duration = models.IntegerField(blank=True, null=True)
    search_string = models.CharField(max_length=10000, blank=True)

    def __str__(self):
        return str(self.generic_control)+" - "+str(self.object)

    def get_absolute_url(self):
        return reverse('cf:controls/control', kwargs={'pk':self.pk})
    
    @property
    def parent(self):
        return self.generic_control

    @property
    def duration(self):
        if self.custom_duration is None:
            return self.frequency.duration
        else:
            return self.custom_duration

    @property
    def policy(self):
        return Policy.objects.filter(generic_policy=self.generic_control.generic_policy,generic_object=self.object.generic_object).first

    class Meta:
        ordering = ['generic_control', 'object']
        unique_together = ('generic_control','object')
        verbose_name = 'Control'
        verbose_name_plural = 'Controls'

django/controlframework/templates/controlframework/controls/control.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- Begin Page Content -->
<div class="container-fluid">

  <!-- Page Heading -->
  <div class="d-flex align-items-center justify-content-between mb-4">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb mb-0">
        <li class="breadcrumb-item"><a href="{% url 'cf:controls' %}">Controls</a></li>
        <li class="breadcrumb-item"><a href="{{ control.generic_control.get_absolute_url }}">{{control.generic_control }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ control }}</li>
      </ol>
    </nav>
  </div>

  <div class="row">
    <div class="col-lg-12">

      <!-- Control Card -->
      <div class="card shadow mb-4">
        <!-- Card Header - Control Title -->
        <div class="card-header py-3">
          <div class="d-flex align-items-center justify-content-between mb-0">
            <h6 class="m-0 font-weight-bold text-primary">{{ control }}
            </h6>
            <div>
              {% if perms.controlframework.delete_control %}
              <!-- Button - Delete -->
              <a href="{% url 'cf:controls/control/delete' control.id %}" class="btn btn-primary btn-icon-split btn-sm">
                <span class="icon text-white-50">
                  <i class="fas fa-trash"></i>
                </span>
                <span class="text d-none d-sm-block">Delete</span>
              </a>
              {% endif %}
              {% if perms.controlframework.change_control %}
              <!-- Button - Edit -->
              <a href="{% url 'cf:controls/control/update' control.id %}" class="btn btn-primary btn-icon-split btn-sm">
                <span class="icon text-white-50">
                  <i class="fas fa-edit"></i>
                </span>
                <span class="text d-none d-sm-block">Edit</span>
              </a>
              {% endif %}
            </div>
          </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
          <!-- Description -->
          <div class="row mb-4">
            <div class="col-12">
              <span class="small font-weight-bold">Description</span><br>
              {{ control.generic_control.description | linebreaks }}
            </div>
          </div>
          <!-- Attributes -->
          <div class="row mb-2">
            <div class="col-6 col-sm-4 mb-2">
              <span class="small font-weight-bold">Frequency</span><br>
              {{control.frequency}}
            </div>
            <div class="col-6 col-sm-4 mb-2">
              <span class="small font-weight-bold">Duration</span><br>
              {{control.duration }} days
            </div>

            <div class="col-6 col-sm-2 mb-2">
              <span class="small font-weight-bold">SOX</span><br>
              {{control.get_sox_display}}
            </div>
            <div class="col-6 col-sm-2 mb-2">
              <span class="small font-weight-bold">PCI</span><br>
              {{control.get_pci_display}}
            </div>
            <div class="col-6 col-sm-4 mb-2">
              <span class="small font-weight-bold">Control Owner</span><br>
              {{ control.owner }}
            </div>
            <div class="col-6 col-sm-4 mb-2">
              <span class="small font-weight-bold">Policy Owner</span><br>
              {{ control.policy.owner }}
            </div>
            <div class="col-6 col-sm-4 mb-2">
              <span class="small font-weight-bold">Accountable</span><br>
              {{ control.policy.accountable}}
            </div>
          </div>
        </div>
      </div>
      <div class="card shadow mb-4">
        <div class="card-header">
          <ul class="nav nav-tabs card-header-tabs" id="controlTab">
          </script>
          <li class="nav-item active">
            <a class="nav-link active" data-toggle="tab" href="#tasks-tab">Tasks</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#scheduler-tab">Scheduler</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#qualityreview-tab">Quality Review</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#issues-tab">Issues</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#evidencerequests-tab">Evidence Requests</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#log-tab">Log</a>
          </li>
        </ul>
      </div>
      <div class="card-body">
        <div class="tab-content">
          <div id="tasks-tab" class="tab-pane active">
            <div class="table-responsive">
              <table class="table table-hover table-striped table-bordered table-condensed" id="taskTable" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <th>Time Slot</th>
                    <th>Task</th>
                    <th class="d-none d-lg-table-cell">Task Title</th>
                    <th>Assignee</th>
                    <th>Created date</th>
                    <th>Due date</th>
                    <th>Days left</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  {% for task in tasks %}
                  <tr>
                    <td>2019 Q3</td>
                    <td class="text-center">
                      <a href = "http://localhost:8080/browse/{{task.issue_key}}" class="badge badge-secondary">{{task.issue_key}}</a>
                    </td>
                    <td class="d-none d-lg-table-cell">{{task.summary}}</td>
                    <td>{{task.assignee_displayname}}</td>
                    <td>{{task.get_created_date}}</td>
                    <td>{{task.get_due_date}}</td>
                    <td>{{task.get_days_left}}</td>
                    <td class="text-center">
                      <span class="badge badge-{{task.get_calculated_status_label_color}}">{{task.get_calculated_status_display}}</span>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
          <div id="scheduler-tab" class="tab-pane">

           <div class="d-flex align-items-center justify-content-between mb-0">
            <span></span>
            <div>
              <!-- Button - Delete -->
              <a href="#scheduler-delete" class="btn btn-primary btn-icon-split btn-sm">
                <span class="icon text-white-50">
                  <i class="fas fa-trash"></i>
                </span>
                <span class="text d-none d-sm-block">Delete</span>
              </a>
              <!-- Button - Edit -->
              <a href="#schedulerEdit" class="btn btn-primary btn-icon-split btn-sm" id="schedulerEdit">
                <span class="icon text-white-50">
                  <i class="fas fa-edit"></i>
                </span>
                <span class="text d-none d-sm-block">Edit</span>
              </a>
            </div>
          </div>

          <form id="schedulerForm">
            <div class="form-group row">
              <div class="col-sm-2">Status</div>
              <div class="col-sm-10">
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" id="statusCheck" value="0">
                  <label class="form-check-label" for="statusCheck">
                    Enabled
                  </label>
                </div>
              </div>
            </div>
            <div class="form-group row">
              <label for="inputSummary" class="col-sm-2 col-form-label">Summary</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" id="inputSummary" placeholder="Summary" value="{{control.control_task.scheduled_task.summary}}">
              </div>
            </div>
            <div class="form-group row">
              <label for="inputDescription" class="col-sm-2 col-form-label">Description</label>
              <div class="col-sm-10">
                <textarea class="form-control" id="inputDescription" placeholder="Description">{{control.control_task.scheduled_task.description}}</textarea>
              </div>
            </div>
            <div class="form-group row">
              <label for="inputAssignee" class="col-sm-2 col-form-label">Assignee</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" id="inputAssignee" placeholder="Assignee" value="{{control.control_task.scheduled_task.assignee}}">
              </div>
            </div>
            <div class="form-group row">
              <label for="inputWatchers" class="col-sm-2 col-form-label">Watchers</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" id="inputWatchers" placeholder="Watchers" value="{{control.control_task.scheduled_task.watchers}}">
              </div>
            </div>
            <div class="form-group row">
              <label for="inputStartDate" class="col-sm-2 col-form-label">Start Date</label>
              <div class="col-sm-4">
                <input type="text" class="form-control" id="inputStartDate" placeholder="Start Date" value="{{control.control_task.scheduled_task.start_date}}">
              </div>
              <label for="inputEndDate" class="col-sm-2 col-form-label">End Date</label>
              <div class="col-sm-4">
                <input type="text" class="form-control" id="inputEndDate" placeholder="End Date" value="{{control.control_task.scheduled_task.end_date}}">
              </div>
            </div>
            <div class="form-group row">
              <label for="inputLastTask" class="col-sm-2 col-form-label">Last Task</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" id="inputLastTask" placeholder="Last Task">
              </div>
            </div>
            <div class="d-flex align-items-center justify-content-between">
              <input type="submit" formnovalidate name="cancel" value="Cancel" class="btn btn-secondary"/>
              <input type="submit" value="Save" class="btn btn-primary"/>
            </div>
          </form>

        </div>
        <div id="qualityreview-tab" class="tab-pane">
          text3
        </div>
        <div id="issues-tab" class="tab-pane">
          text4
        </div>
        <div id="evidencerequests-tab" class="tab-pane">
          text5
        </div>
        <div id="log-tab" class="tab-pane">
          text6
        </div>
      </div>
    </div>
  </div>
</div>

  {% endblock content %}

django/controlframework/templates/controlframework/controls/genericcontrol.html
{% extends 'base.html' %}

{% block content %}

<!-- Begin Page Content -->
<div class="container-fluid">

	<!-- Page Heading -->
	<div class="d-flex align-items-center justify-content-between mb-4">

		<nav aria-label="breadcrumb">
			<ol class="breadcrumb mb-0">
				<li class="breadcrumb-item"><a href="{% url 'cf:controls' %}">Controls</a></li>
				<li class="breadcrumb-item active" aria-current="page">{{ genericcontrol }}</li>
			</ol>
		</nav>
	</div>

	<div class="row">
		<div class="col-lg-6">
			<!-- Generc Object Card -->
			<div class="card shadow mb-4">
				<!-- Card Header -->
				<div class="card-header py-3">
					<div class="d-flex align-items-center justify-content-between mb-0">
						<!-- Generic Object-->
						<h6 class="m-0 font-weight-bold text-primary">{{ genericcontrol }}</h6>
						<div>
							{% if perms.controlframework.add_genericcontrol %}
							<!-- Button - New -->
							<a href="{% url 'cf:controls/control/add/genericcontrol' genericcontrol.id %}" class="btn btn-primary btn-icon-split btn-sm">
								<span class="icon text-white-50">
									<i class="fas fa-plus"></i>
								</span>
								<span class="text d-none d-sm-block">New Control</span>
							</a>
							{% endif %}
							{% if perms.controlframework.delete_genericcontrol%}
							<!-- Button - Delete -->
							<a href="{% url 'cf:controls/genericcontrol/delete' genericcontrol.id %}" class="btn btn-primary btn-icon-split btn-sm">
								<span class="icon text-white-50">
									<i class="fas fa-trash"></i>
								</span>
								<span class="text d-none d-sm-block">Delete</span>
							</a>
							{% endif %}
							{% if perms.controlframework.change_genericcontrol %}
							<!-- Button - Edit -->
							<a href="{% url 'cf:controls/genericcontrol/update' genericcontrol.id %}" class="btn btn-primary btn-icon-split btn-sm">
								<span class="icon text-white-50">
									<i class="fas fa-edit"></i>
								</span>
								<span class="text d-none d-sm-block">Edit</span>
							</a>
							{% endif %}
						</div>
					</div>
				</div>
				<!-- Card Body -->
				<div class="card-body">
					<p>
						<span class="small">Description</span><br>
						{{ genericcontrol.description | linebreaks }}
					</p>
					<p>
						<span class="small">Linked Controls</span><br>
						{% for control in genericcontrol.controls.all %}
						<a class="float-left text-secondary" href="{{ control.get_absolute_url }}">{{ control }}</a><br>

						{% endfor %}
					</p>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock content %}